version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - nodenginx

  node-app:
    build:
      context: ./node
    image: daquadra/node
    container_name: node-app
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://mariadb:3306",
        "-timeout",
        "30s",
        "nodemon",
        "index.js",
      ]
    ports:
      - "3000:3000"
    volumes:
      - ./node/app/:/usr/src/app
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=fullcycle
    networks:
      - nodenginx
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./nginx
    image: daquadra/nginx
    container_name: nginx
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://mariadb:3306",
        "-wait",
        "http://node-app:3000",
        "-timeout",
        "30s",
        "nginx",
        "-g",
        "daemon off;",
      ]
    ports:
      - "8080:80"
    depends_on:
      - node-app
    networks:
      - nodenginx

networks:
  nodenginx:
    driver: bridge
