version: "3"

services:
  node-app:
    build:
      context: ./node
    image: daquadra/node:withNginx
    container_name: node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node/app/:/usr/src/app

  nginx:
    build:
      context: ./nginx
    image: daquadra/nginx:node
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/desfaut.conf
    depends_on:
      - node-app
